### ISSUE TITLE
shits fucking broken

### ISSUE THREAD

**Issue by KitOdin** [i-winxd/THIRTY-DOLLAR-HAIRCUT-GENERATOR#1]
![image](https://user-images.githubusercontent.com/79374666/176321586-a46ae630-e1cd-4271-a9f4-9f866427cf30.png)
i cant even run the program cause the syntax is all messed up!
(python version is 3.7 btw)

**Comment by i-winxd** [comment]
# Please use Python 3.10!!!! Your Python version is outdated.

The program won't work otherwise. I can see that type annotations are messing up your Python interpreter. This program is explicitly incompatible with any Python version earlier than 3.10 (not even 3.9).
